### ISSUE TITLE
Cuidado ao mudar os nomes de atributos, variáveis, etc.

### ISSUE THREAD

**Issue by flaviohenriquealmeida** [lucascc26/contatooh#1]
Você mudou o nome de várias atributos e variáveis do livro. Se você não quis seguir o que está lá, tudo bem, pode mudar, mas tenha certeza que mudou em todos os lugares os nomes dessas variáveis e seus atributos. 

Você não consegue se autenticar no Github porque quiz alterar o nome dos atributos do model `User.js`. Você usa `login` e `name`, mas na hora de consultar o banco em seu `passport.js` usa `login` e **nome**, é por isso que você esta tendo um erro de validação, o campo `name` nunca é gravado e ele é required no seu modelo.

Fechei sua issue no repositório, porque isso é mais pergunta de fórum do que issue no código da aplicação.

Só penso uma atenção redobrada nos nomes dos arquivos, variáveis, etc já que você optou por mudá-los.

Abraço e bom estudo!

**Comment by lucascc26** [comment]
Muito obrigado, Flávio! Testarei a solução assim que puder. Entrei também na comunidade do Facebook.

Abraço!

**Comment by flaviohenriquealmeida** [comment]
Não deixa de me passar um Feedback!  Só alterar seu passport.js.

Sucesso e bom estudo.

**Comment by lucascc26** [comment]
Olá, Flávio. A solução funcionou. Muito obrigado!

Agora estou com outro problema, segue o log do Travis:
Mongoose! Conectado em mongodb://localhost/contatooh

ERROR - Unable to start a WebDriver session.

/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113

  var template = new Error(this.message);

                 ^

UnknownError: unknown error: Chrome failed to start: crashed

  (Driver info: chromedriver=2.12.301324 (de8ab311bc9374d0ade71f7c167bad61848c7c48),platform=Linux 3.13.0-40-generic x86_64)

    at new bot.Error (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)

    at Object.bot.response.checkResponse (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)

    at /home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24

    at /home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15

    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)

    at notify (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)

    at notifyAll (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)

    at resolve (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)

    at fulfill (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)

    at /home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/base.js:1582:15

==== async task ====

WebDriver.createSession()

    at Function.webdriver.WebDriver.acquireSession_ (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)

    at Function.webdriver.WebDriver.createSession (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)

    at new Driver (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:477:36)

    at Object.createDriver (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:453:10)

    at DirectDriverProvider.getNewDriver (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/lib/driverProviders/direct.js:68:23)

    at Runner.createBrowser (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/lib/runner.js:178:37)

    at /home/travis/.nvm/v0.10.40/lib/node_modules/protractor/lib/runner.js:259:24

    at _fulfilled (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/q/q.js:797:54)

    at self.promiseDispatch.done (/home/travis/.nvm/v0.10.40/lib/node_modules/protractor/node_modules/q/q.js:826:30)

[launcher] Process exited with error code 1

The command "protractor config/protractor.js" exited with 1.
sauce_connect.stop

Stopping Sauce Connect

5.01s$ travis_stop_sauce_connect

Waiting for graceful Sauce Connect shutdown

22 Sep 03:00:07 - Cleaning up.

22 Sep 03:00:08 - Shutting down named tunnel 4.1 (d00efcc72941485386d4498d0abe01af).

Waiting for graceful Sauce Connect shutdown

Waiting for graceful Sauce Connect shutdown

Waiting for graceful Sauce Connect shutdown

Waiting for graceful Sauce Connect shutdown

22 Sep 03:00:11 - Goodbye.

Sauce Connect shutdown complete

Done. Your build exited with 1.

/home/travis/build.sh: line 103:  2730 Killed                  node server

Pode me ajudar?

Obrigado novamente.

**Comment by flaviohenriquealmeida** [comment]
Ajudo no fórum, aqui não. Esse espaço e para issues.
Em 22/09/2015 00:09, "lucascc26" <notifications@github.com> escreveu:

**Comment by lucascc26** [comment]
Ok, minha solicitação ainda está pendente.
